import java.security.MessageDigest
import groovy.json.JsonSlurper
import org.gradle.api.artifacts.component.ModuleComponentIdentifier
import org.gradle.api.artifacts.component.ProjectComponentIdentifier

plugins {
    `java-library`
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.21"
    id("com.gradleup.shadow") version "9.0.0"
}

val itemBridgeInput by configurations.creating {
    isCanBeConsumed = false
    isTransitive = false
}

// Keep ItemBridge's core and external providers. Its discovery implementation eagerly links
// excluded providers, so a separately attributed discovery source is compiled below.
val itemBridgeRuntime by tasks.registering(Jar::class) {
    archiveFileName.set("itembridge-1.0.32-filtered.jar")
    destinationDirectory.set(layout.buildDirectory.dir("dependencies"))
    from(provider { zipTree(itemBridgeInput.singleFile) })
    exclude("cn/gtemc/itembridge/hook/NeigeItemsProvider*.class",
        "cn/gtemc/itembridge/hook/SXItemProvider*.class",
        "cn/gtemc/itembridge/hook/HookHelper*.class")
    doFirst {
        val digest = MessageDigest.getInstance("SHA-256")
            .digest(itemBridgeInput.singleFile.readBytes()).joinToString("") { "%02x".format(it) }
        check(digest == "07276894b33aa8ee7c3b9d2969295b40668aafcbaa75d3049de1bc659c99054e") {
            "ItemBridge input changed; review the provider filter and discovery source before updating"
        }
    }
}

dependencies {
    add("paperweightDevelopmentBundle", "io.papermc.paper:dev-bundle:26.2.build.123-stable@zip")
    api(project(":core"))
    implementation(project(":compat-ni"))
    implementation(project(":compat-sx"))
    implementation(project(":keystone-runtime"))
    add(itemBridgeInput.name, "cn.gtemc:itembridge:1.0.32")
    implementation(files(itemBridgeRuntime))
    compileOnly("me.clip:placeholderapi:2.12.3")
    compileOnly("org.openjdk.nashorn:nashorn-core:15.4")
}

sourceSets.main { java.srcDir(rootProject.file("vendor/itembridge/src/main/java")) }

val verifyRuntimeInputs by tasks.registering {
    val inventory = rootProject.file("provenance/runtime-dependencies.json")
    inputs.file(inventory)
    inputs.files(configurations.runtimeClasspath)
    doLast {
        val manifest = JsonSlurper().parse(inventory) as Map<*, *>
        val expected = (manifest["runtime_artifacts"] as List<*>).associate {
            val row = it as Map<*, *>
            row["coordinate"].toString() to row["sha256"].toString()
        }
        val actual = configurations.runtimeClasspath.get().incoming.artifacts.artifacts
            .mapNotNull { artifact ->
                val component = artifact.id.componentIdentifier
                if (component !is ModuleComponentIdentifier) {
                    val input = artifact.file.canonicalFile
                    if (component is ProjectComponentIdentifier) {
                        check(component.projectPath in setOf(":core", ":compat-ni", ":compat-sx", ":keystone-runtime")) {
                            "Unreviewed runtime project: $component"
                        }
                        val expectedJar = project(component.projectPath).tasks.named<Jar>("jar")
                            .get().archiveFile.get().asFile.canonicalFile
                        check(input == expectedJar) { "Unexpected runtime project artifact: $input" }
                    } else {
                        check(input == itemBridgeRuntime.get().archiveFile.get().asFile.canonicalFile) {
                            "Unreviewed runtime file dependency: $input"
                        }
                    }
                    return@mapNotNull null
                }
                val key = "${component.group}:${component.module}:${component.version}"
                val hash = MessageDigest.getInstance("SHA-256").digest(artifact.file.readBytes())
                    .joinToString("") { "%02x".format(it) }
                key to hash
            }.toMap()
        check(actual == expected) { "Runtime dependency inputs changed; review exact binaries, sources and legal notices" }
    }
}

tasks.withType<JavaCompile>().configureEach { options.release.set(25) }
tasks.jar { manifest.attributes["paperweight-mappings-namespace"] = "mojang" }

tasks.processResources {
    inputs.property("version", project.version)
    filesMatching("plugin.yml") { expand("version" to project.version) }
}

tasks.shadowJar {
    dependsOn(verifyRuntimeInputs)
    archiveFileName.set("ItemLoom-${project.version}.jar")
    archiveClassifier.set("plugin")
    relocate("dev.keystone", "dev.itemloom.internal.keystone")
    relocate("cn.gtemc.itembridge", "dev.itemloom.internal.itembridge")
    // Nashorn's generated bytecode contains embedded descriptors. Shadow relocation breaks
    // NativeArray construction; retain its own namespace and verify the packaged engine.
    relocate("org.objectweb.asm", "dev.itemloom.internal.asm")
    relocate("net.momirealms.sparrow.yaml", "dev.itemloom.internal.keystone.libs.sparrow.yaml")
    mergeServiceFiles()
    exclude("META-INF/*.SF", "META-INF/*.RSA", "META-INF/*.DSA", "module-info.class", "META-INF/versions/*/module-info.class")
    from(rootProject.file("LICENSE"))
    from(rootProject.file("NOTICE.md"))
    from(rootProject.file("licenses")) { into("META-INF/licenses") }
    from(rootProject.file("provenance/runtime-dependencies.json")) { into("META-INF/licenses") }
    from(rootProject.file("vendor/itembridge/README.md")) {
        into("META-INF/licenses")
        rename { "itembridge-modifications.md" }
    }
    manifest.attributes["paperweight-mappings-namespace"] = "mojang"
}
tasks.assemble { dependsOn(tasks.shadowJar) }

val probe by sourceSets.creating {
    compileClasspath += sourceSets.main.get().output + configurations.compileClasspath.get()
    runtimeClasspath += output + compileClasspath
}
tasks.register<Jar>("probeJar") {
    dependsOn(tasks.named(probe.classesTaskName))
    archiveFileName.set("ItemLoomProbe.jar")
    from(probe.output)
    manifest.attributes["paperweight-mappings-namespace"] = "mojang"
}
