plugins {
    `java-library`
    id("io.papermc.paperweight.userdev") version "2.0.0-beta.21"
    id("com.gradleup.shadow") version "9.0.0"
}

dependencies {
    add("paperweightDevelopmentBundle", "io.papermc.paper:dev-bundle:26.2.build.123-stable@zip")
    api(project(":core"))
    implementation(project(":compat-ni"))
    implementation(project(":compat-sx"))
    implementation(project(":keystone-runtime"))
    compileOnly("me.clip:placeholderapi:2.12.3")
    compileOnly("org.openjdk.nashorn:nashorn-core:15.4")
}

tasks.withType<JavaCompile>().configureEach { options.release.set(25) }
tasks.jar { manifest.attributes["paperweight-mappings-namespace"] = "mojang" }

tasks.processResources {
    inputs.property("version", project.version)
    filesMatching("plugin.yml") { expand("version" to project.version) }
}

tasks.shadowJar {
    archiveFileName.set("ItemLoom-${project.version}.jar")
    archiveClassifier.set("plugin")
    relocate("dev.keystone", "dev.itemloom.internal.keystone")
    // Nashorn's generated bytecode contains embedded descriptors. Shadow relocation breaks
    // NativeArray construction; retain its own namespace and verify the packaged engine.
    relocate("org.objectweb.asm", "dev.itemloom.internal.asm")
    relocate("net.momirealms.sparrow.yaml", "dev.itemloom.internal.keystone.libs.sparrow.yaml")
    mergeServiceFiles()
    exclude("META-INF/*.SF", "META-INF/*.RSA", "META-INF/*.DSA", "module-info.class", "META-INF/versions/*/module-info.class")
    from(rootProject.file("LICENSE"))
    from(rootProject.file("NOTICE.md"))
    manifest.attributes["paperweight-mappings-namespace"] = "mojang"
}
tasks.assemble { dependsOn(tasks.shadowJar) }

val probe by sourceSets.creating {
    compileClasspath += sourceSets.main.get().output + configurations.compileClasspath.get()
    runtimeClasspath += output + compileClasspath
}
tasks.register<Jar>("probeJar") {
    dependsOn(tasks.named(probe.classesTaskName))
    archiveFileName.set("ItemLoomProbe.jar")
    from(probe.output)
    manifest.attributes["paperweight-mappings-namespace"] = "mojang"
}
