package dev.itemloom.paper.integration;

import java.util.Locale;
import java.util.Set;

/** Explicit source grammar; the item id after the second colon is preserved as one value. */
public record ExternalItemMaterial(String provider, String id) {
    private static final String PREFIX = "itembridge:";
    private static final Set<String> FORBIDDEN =
            Set.of("ni", "neigeitems", "sx", "sxitem", "sx-item", "itemloom");

    public ExternalItemMaterial {
        if (provider == null || provider.isBlank() || id == null || id.isBlank())
            throw new IllegalArgumentException(
                    "External material requires itembridge:<provider>:<item ID>");
        provider = provider.strip().toLowerCase(Locale.ROOT);
        id = id.strip();
        if (provider.indexOf(':') >= 0)
            throw new IllegalArgumentException("Invalid ItemBridge provider: " + provider);
        requireAllowed(provider);
    }

    public static boolean isExternal(String value) {
        return value != null && value.strip().regionMatches(true, 0, PREFIX, 0, PREFIX.length());
    }

    public static ExternalItemMaterial parse(String value) {
        if (!isExternal(value))
            throw new IllegalArgumentException(
                    "External material requires itembridge:<provider>:<item ID>: " + value);
        String body = value.strip().substring(PREFIX.length());
        int split = body.indexOf(':');
        if (split <= 0 || split == body.length() - 1)
            throw new IllegalArgumentException("Malformed external material: " + value);
        return new ExternalItemMaterial(body.substring(0, split), body.substring(split + 1));
    }

    static boolean allowed(String provider) {
        return !FORBIDDEN.contains(provider.strip().toLowerCase(Locale.ROOT));
    }

    static void requireAllowed(String provider) {
        if (!allowed(provider))
            throw new IllegalArgumentException(
                    "External item provider '"
                            + provider
                            + "' is disabled; NI/SX definitions are generated by ItemLoom itself");
    }
}
